[package]
name = "mp-digest-log"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Primitives for Madara digest logs"
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
mp-block = { workspace = true, features = ["parity-scale-codec"] }
parity-scale-codec = { workspace = true }
sp-runtime = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
