[package]
name = "mp-digest-log"
version = "0.1.0-alpha"
license = "MIT"
description = "Primitives for Madara digest logs"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
mp-starknet = { workspace = true }
scale-codec = { package = "parity-scale-codec", workspace = true, default-features = false }
# Substrate
sp-runtime = { workspace = true }
thiserror-no-std = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"

[features]
default = ["std"]
std = ["mp-starknet/std", "scale-codec/std", "sp-runtime/std"]
