[package]
name = "mp-digest-log"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Primitives for Madara digest logs"
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
mp-starknet = { workspace = true }
scale-codec = { workspace = true }
# Substrate
sp-runtime = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"

[features]
default = ["std"]
std = ["mp-starknet/std", "scale-codec/std", "sp-runtime/std"]
