[package]
name = "mp-starknet-inherent"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Sequencer address inherent logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { workspace = true }
sp-inherents = { workspace = true }
thiserror = { workspace = true }
blockifier = { workspace = true }

# Optional
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = [
    "derive",
], optional = true }
scale-info = { workspace = true, optional = true }

[features]
parity-scale-codec = ["dep:parity-scale-codec"]
scale-info = ["dep:scale-info"]
client = ["parity-scale-codec", "dep:async-trait"]
