[package]
name = "mp-sequencer-address"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Sequencer address inherent logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { workspace = true }
sp-inherents = { workspace = true }
thiserror-no-std = { workspace = true }

# Optional
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }

[features]
default = ["std"]
std = ["sp-inherents/std", "thiserror-no-std/std", "parity-scale-codec?/std"]
parity-scale-codec = ["dep:parity-scale-codec"]
client = ["std", "parity-scale-codec", "dep:async-trait"]
