version: "3.2"

services:
  dev:
    container_name: madara
    image: paritytech/ci-linux:production
    working_dir: /var/www/madara
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/madara/.cargo
    volumes:
      - ../../:/var/www/madara
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/madara --dev --ws-external"
