[package]
name = "mp-transactions"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet primitives for Substrate."
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
cairo-vm = { workspace = true }
indexmap = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
sha3 = { workspace = true }
sp-core = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }
starknet-ff = { workspace = true, features = ["alloc"] }
starknet_api = { workspace = true }

# Optional (client)
cairo-lang-starknet-classes = { workspace = true, optional = true }
cairo-lang-utils = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
num-bigint = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

# Other optional
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
log = "0.4.20"

[dev-dependencies]
assert_matches = "1.5.0"

[features]
client = [
  "dep:flate2",
  "dep:cairo-lang-utils",
  "dep:num-bigint",
  "dep:serde_json",
  "dep:thiserror",
  "dep:cairo-lang-starknet-classes",
]
parity-scale-codec = [
  "dep:parity-scale-codec",
  "starknet_api/parity-scale-codec",
  "mp-felt/parity-scale-codec",
]
scale-info = [
  "dep:scale-info",
  "mp-felt/scale-info",
  "starknet_api/scale-info",
  "blockifier/scale-info",
]
serde = ["dep:serde", "mp-felt/serde"]
