version: "3.2"

services:
  madara:
    image: ghcr.io/keep-starknet-strange/madara:latest
    ports:
      - "9933:9933"
      - "9615:9615"
      - "9944:9944"
      - "30333:30333"
    platform: linux/x86_64
    command:
      - "--prometheus-external"
      - "--rpc-cors=all"
      - "--rpc-external"
      - "--ws-external"

  madara-app:
    image: ghcr.io/keep-starknet-strange/madara-app:latest
    ports:
      - "8080:80"
    environment:
      WS_URL: "ws://0.0.0.0:9944"

  starkcet-front:
    image: ghcr.io/zizou0x/starkcet-frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - starkcet-back
    networks:
      - faucet
      
  starkcet-back:
    image: ghcr.io/zizou0x/starkcet-backend:latest
    environment:
      - PRIVATE_KEY=0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d
      - STARKNET_ACCOUNT_ADDRESS=0x2
      - TOKEN_ADDRESS=0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d01
      - RPC_URL=http://host.docker.internal:9944
      - AMOUNT_TRANSFERED=1000000000000000
    networks:
      - faucet

networks:
  faucet:
