[package]
name = "mc-state-sync"
version = "0.1.0"
description = "Sync state from L1."
homepage = "https://github.com/keep-starknet-strange/madara"
edition.workspace = true
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[dependencies]
tokio = { workspace = true, features = ["macros", "test-util", "rt-multi-thread"] }
futures = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
indexmap = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }

# Madara
mp-hashers = { workspace = true, default-features = true }
mp-commitments = { workspace = true, default-features = true }
mp-digest-log = { workspace = true }
mc-rpc-core = { workspace = true }
mp-block = { workspace = true }
mp-storage = { workspace = true  }
mc-db = { workspace = true }
mc-mapping-sync = { workspace = true }
madara-runtime = { workspace = true }
pallet-starknet = { workspace = true }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }

# Starknet
blockifier = { workspace = true, default-features = true }
starknet_api = { workspace = true }

# Substrate
frame-support = { workspace = true }
sp-runtime = { workspace = true }
sp-blockchain = { workspace = true }
sp-state-machine = { workspace = true }
sp-core = { workspace = true }
sp-api = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { workspace = true }

# Ethereum
ethers = "2.0.11"
tokio-retry = "0.3.0"

[dev-dependencies]
pretty_assertions = { workspace = true }

# Substrate
sc-block-builder = { workspace = true }
sp-inherents = { workspace = true }
sp-timestamp = { workspace = true }
sp-block-builder = { workspace = true }
substrate-test-client = { workspace = true }

# Starknet
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }

# Madara
mp-transactions = { workspace = true }

const-decoder = "0.3.0"
httpmock = "0.7.0-rc.1"
project-root = "0.2.2"
test-case = "3.1.0"
lazy_static = "1.4.0"
hexlit = "0.5.5"
assert_matches = "1.5.0"
tempfile = "3.8.1"
