
[package]
name = "mc-storage"
version.workspace = true
edition.workspace = true
description = "Starknet storage compatibility layer for Substrate."
authors = [
  "Timoth√©e Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[dependencies]
blockifier = { workspace = true, features = ["std"] }
frame-support = { workspace = true, features = ["std"] }
frame-system = { workspace = true, features = ["std"] }
madara-runtime = { workspace = true, features = ["std"] }
mp-storage = { workspace = true, features = ["std"] }
pallet-starknet = { workspace = true, features = ["std"] }
pallet-starknet-runtime-api = { workspace = true, features = ["std"] }
parity-scale-codec = { workspace = true, features = ["std"] }
sc-client-api = { workspace = true }
sp-api = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-storage = { workspace = true, features = ["std"] }
starknet-core = { workspace = true, features = ["std"] }
starknet_api = { workspace = true, features = ["std"] }
