[package]
name = "mp-program-hash"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet program hashes"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara Primitives
mp-felt = { workspace = true }
# Starknet dependencies
starknet-ff = { workspace = true }

[features]
default = ["std"]
std = ["mp-felt/std"]
