---
name: Task - Build & Integration Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_build_test:
    runs-on: ubuntu-latest-32-cores
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: actions/cache@v3
        with:
          path: |
            target/production/madara
          key:
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Setup rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: rustup show

      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler

      - name: Build the project
        run: |
          cargo build --profile production --workspace

      - name: Run integration tests
        run: cargo test --release
