---
name: Task - Rpc Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rpc-tests:
    runs-on: ubuntu-latest
    env:
      BINARY_PATH: ../target/release/madara
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
          save-if: false
      - uses: actions/cache@v3
        with:
          path: target/release/madara
          key:
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          fail-on-cache-miss: true
      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler
      - name: Setup dev chain
        run: |
          ./target/release/madara setup --chain=dev --from-remote
      - name: Run rpc native test
        run: |-
          ./target/release/madara --dev --sealing=manual --execution=Native &
          NATIVE_RUN_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          cd starknet-rpc-test
          cargo test
          kill $NATIVE_RUN_PID
      - name: Run rpc wasm test
        run: |-
          ./target/release/madara --dev --sealing=manual --execution=Wasm &
          WASM_RUN_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          cd starknet-rpc-test
          cargo test
          kill $WASM_RUN_PID
