name: Starknet-js Compatibility Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BINARY_PATH: ../target/production/madara
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            target/production/madara
          key:
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          fail-on-cache-miss: true
      - name: Setup dev chain
        run: |
          ./target/production/madara setup --chain=dev --from-local=configs
      - name: Run starknet-js test
        run: |-
          ./target/production/madara --dev &
          MADARA_RUN_PID=$!
          while ! echo exit | nc localhost 9944; do sleep 1; done
          git clone https://github.com/keep-starknet-strange/sequencer-js-compatibility-tests.git
          cd sequencer-js-compatibility-tests
          npm install
          npm test
          kill $MADARA_RUN_PID
